# Generated by Django 2.2 on 2022-02-14 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Demo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='prerequisite',
            field=models.ManyToManyField(to='Demo.Course'),
        ),
    ]
